### PR TITLE
Integrate Google Translation API

### PR DESCRIPTION
**Pull request by carissaallen**
## Overview
Integrates the [Google Translation API](https://cloud.google.com/translate/docs/reference/rest/v2/translate#body.QUERY_PARAMETERS) to translate the page containing the top three reviews generated by the Yelp API into a language of the user's choice. The language must be available in the dropdown menu provided.

### CODE REVIEW

**Comment by rooneyshuman** [comment]
Recent changes seem to have increased the latency to the translation API and as a result the number of errors received.
* Error received:
Screen Shot 2019-12-05 at 7 45 31 PM
* GET request being executed:
Screen Shot 2019-12-05 at 7 48 04 PM
* API dashboard showing increased latency in 12/4 vs 12/5:
Screen Shot 2019-12-05 at 7 49 10 PM

**Comment by carissaallen** [comment]
It appears that when a Yelp user image is missing, although we include an `onerror` HTML attribute to display a default image, it still seems to trigger a second hit to the translation endpoint. Since this is not initiated by the user by selecting a language from the dropdown menu, a target language is not passed in to the GET request.

The fix is to check whether "None" is passed in to the GET request instead of the target language, and if so, to return from the endpoint to prevent hitting the Google Translation API without a target language (which produces an unnecessary error since the page has already been successfully translated).

**Review by rooneyshuman — APPROVED** [review]
This PR successfully integrates the google translation API.
Alt Text

**Pull request merged**
